#yaml file if you want to use Google App Engine to run this

runtime: python37

entrypoint: gunicorn -b :$PORT main:app --timeout 120

instance_class: F4_1G

env_variables:
    NLTK_DATA: './nltk_data'
